SOURCES += main.cpp mainwindow.cpp clienttcpsocket.cpp
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets
DEFINES += QT_DEPRECATED_WARNINGS
HEADERS += mainwindow.h clienttcpsocket.h
FORMS += mainwindow.ui
LIBS += -lssl -lcrypto
QT += core gui network
TARGET = Client
TEMPLATE = app
