# STARTING THE INSTALLATION PROCESS

# INSTALLING THE DEPENDENCIES
echo "[1/4] INSTALLING THE DEPENDENCIES"
sudo apt install $(cat Requirements.txt)

# MAKING A QMAKE.STASH FILE
echo "[2/4] MAKING A QMAKE.STASH FILE"
qmake Photon-Compiler.pro

# COMPILING THE SERVER & BINARY FILE
echo "[3/4] COMPILING THE SERVER & BINARY FILE"
make

# COPYING THE FILES TO ROOT DIRECTORY
echo "[4/4] COPYING THE FILES TO ROOT DIRECTORY"
mv ./Server/Server .
mv ./Client/Client .

# INSTALLATION COMPLETED
echo "### INSTALLATION COMPLETED"
