SOURCES += main.cpp chatserver.cpp clienthandlerthread.cpp customtcpsocket.cpp
HEADERS += chatserver.h clienthandlerthread.h customtcpsocket.h
DEFINES += QT_DEPRECATED_WARNINGS
CONFIG += c++11 console
CONFIG -= app_bundle
LIBS += -lssl -lcrypto
QT += core network
QT -= gui
TARGET = Server
